#- hosts: all
#  tasks:
#    name: aptinstall
#    become: yes
#    apt: name={{ item }} update_cache=yes cache_valid_time=3600
#    with_items:
#      - neovim
#      - fish
#      - tmux
- hosts: localhost
  user: kakkyz
  tasks:
  - name: aptinstall
    become: yes
    apt: 
      name: [neovim, tmux, fish, git, taskwarrior]
  - name: setupgit
    shell: git config --global user.email "kakkyz81@mail.com" &&
           git config --global user.name "kakkyz" &&
           git config --global alias.st status &&
           git config --global alias.ci commit 
  - name: filescopy
    copy: src=files/dotfiles dest=~/ force=yes
  - name: bincopy 
    copy: src=files/bin dest=~/ 
  - name: chmod-bin-dir
    shell: chmod 744 ~/bin/*
  - name: link-dotfiles
    shell: bash ~/dotfiles/install.sh
    args:
      chdir: ~/dotfiles
